[package]
name = "libgitdit"
version = "0.5.0"
description = "A library for distributed issue tracking in git"
authors = ["Matthias Beyer <mail@beyermatthias.de>",
           "Julian Ganz <neither@nut.email>"]
license = "MPL-2.0"

[dependencies]
git2 = "0.17"
regex = "1"
lazy_static = "1"
